name: video_formatter
description: A video formatter to format workout takes in the expected format by the Hulki's applications.
version: 1.0.0
homepage: https://hulki.com.br/

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
